package io.github.camilyed.clickhouse.r2dbc.connector;

import com.clickhouse.jdbc.ClickHouseDriver;
import io.github.camilyed.clickhouse.r2dbc.testkit.BaseClickHouseIntegrationTest;
import io.r2dbc.spi.ConnectionFactories;
import io.r2dbc.spi.ConnectionFactory;
import io.r2dbc.spi.ConnectionFactoryOptions;
import io.r2dbc.spi.test.TestKit;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.springframework.jdbc.core.JdbcOperations;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SimpleDriverDataSource;

/**
 * Runs the official R2DBC SPI Technology Compatibility Kit ({@code io.r2dbc:r2dbc-spi-test}'s
 * {@link TestKit}) against this driver over a real ClickHouse server — the precise, written answer
 * to "where does this driver match the R2DBC SPI, and where does ClickHouse deliberately not have
 * that semantic" (ROADMAP.md Phase 7 item 7). Every {@link Disabled} override below documents
 * exactly why that one SPI behavior doesn't apply here, rather than silently skipping it — see
 * {@code docs/R2DBC_COMPATIBILITY.md} for the same information written up as a standalone table.
 *
 * <p>{@link #getJdbcOperations()} needs a JDBC connection to the same ClickHouse server the R2DBC
 * {@link ConnectionFactory} under test connects to, purely so the TCK can set up/tear down its own
 * fixture tables outside of this driver's own code path — the TCK's own design, not something this
 * test invented (see {@link TestKit}'s own Javadoc). {@code com.clickhouse:clickhouse-jdbc} and
 * {@code org.springframework:spring-jdbc} are test-only dependencies of this module for exactly
 * that reason; neither is ever a production dependency of this driver.
 *
 * <p>The parameter placeholder type is always {@code Nullable(Int32)} (see {@link
 * #getPlaceholder}): every TCK test that binds a value binds either an {@code Integer} or {@code
 * null}, and ClickHouse requires a column/parameter to be explicitly {@code Nullable(...)} before a
 * {@code NULL} can be bound to it at all.
 */
class ClickHouseR2dbcSpiCompatibilityTest extends BaseClickHouseIntegrationTest
    implements TestKit<String> {

  private final ConnectionFactory connectionFactory = buildConnectionFactory();
  private final JdbcOperations jdbcOperations = buildJdbcOperations();

  private static ConnectionFactory buildConnectionFactory() {
    final URI httpUrl = URI.create(clickHouseHttpUrl());
    return ConnectionFactories.get(
        ConnectionFactoryOptions.builder()
            .option(ConnectionFactoryOptions.DRIVER, "clickhouse")
            .option(ConnectionFactoryOptions.HOST, httpUrl.getHost())
            .option(ConnectionFactoryOptions.PORT, httpUrl.getPort())
            .option(ConnectionFactoryOptions.USER, clickHouseUsername())
            .option(ConnectionFactoryOptions.PASSWORD, clickHousePassword())
            .build());
  }

  private static JdbcOperations buildJdbcOperations() {
    final SimpleDriverDataSource dataSource = new SimpleDriverDataSource();
    dataSource.setDriverClass(ClickHouseDriver.class);
    dataSource.setUrl("jdbc:clickhouse:" + clickHouseHttpUrl());
    dataSource.setUsername(clickHouseUsername());
    dataSource.setPassword(clickHousePassword());
    return new JdbcTemplate(dataSource);
  }

  @Override
  public ConnectionFactory getConnectionFactory() {
    return connectionFactory;
  }

  @Override
  public JdbcOperations getJdbcOperations() {
    return jdbcOperations;
  }

  @Override
  public String getPlaceholder(final int index) {
    return "{p" + index + ":Nullable(Int32)}";
  }

  @Override
  public String getIdentifier(final int index) {
    return "p" + index;
  }

  @Override
  public String blobType() {
    // ClickHouse has no BLOB type - String is the closest fit, and is only needed to keep
    // createTable()'s DDL valid; the tests that would actually exercise this column (blobInsert,
    // blobSelect) are disabled below.
    return "String";
  }

  @Override
  public String clobType() {
    return "String";
  }

  @Override
  public String doGetSql(final TestStatement statement) {
    return switch (statement) {
      case CREATE_TABLE -> "CREATE TABLE test (test_value Nullable(Int32)) ENGINE = Memory";
      case CREATE_TABLE_TWO_COLUMNS ->
          "CREATE TABLE test_two_column (col1 Int32, col2 String) ENGINE = Memory";
      case CREATE_BLOB_TABLE -> "CREATE TABLE blob_test (test_value %s) ENGINE = Memory";
      case CREATE_CLOB_TABLE -> "CREATE TABLE clob_test (test_value %s) ENGINE = Memory";
      case CREATE_TABLE_AUTOGENERATED_KEY ->
          "CREATE TABLE test (id UInt64, test_value Nullable(Int32)) ENGINE = Memory";
      default -> statement.getSql();
    };
  }

  // -----------------------------------------------------------------------------------------
  // Transactions/savepoints: ClickHouse's HTTP interface has no session-scoped transaction
  // state this driver could implement against - see ClickHouseConnection's own class Javadoc
  // (checked directly against ClickHouse's "Transactional (ACID) support" docs) for why every
  // transaction/savepoint method fails clearly with UnsupportedOperationException instead.
  // -----------------------------------------------------------------------------------------

  @Disabled("ClickHouse: no transaction support over this driver's stateless HTTP interface")
  @Override
  public void changeAutoCommitCommitsTransaction() {}

  @Disabled("ClickHouse: no transaction support over this driver's stateless HTTP interface")
  @Override
  public void sameAutoCommitLeavesTransactionUnchanged() {}

  @Disabled("ClickHouse: no transaction support over this driver's stateless HTTP interface")
  @Override
  public void transactionCommit() {}

  @Disabled("ClickHouse: no transaction support over this driver's stateless HTTP interface")
  @Override
  public void transactionRollback() {}

  @Disabled(
      "ClickHouse: no savepoint support (requires a transaction, which this driver doesn't implement)")
  @Override
  public void savePoint() {}

  @Disabled(
      "ClickHouse: no savepoint support (requires a transaction, which this driver doesn't implement)")
  @Override
  public void savePointStartsTransaction() {}

  // -----------------------------------------------------------------------------------------
  // BLOB/CLOB: ClickHouse has no distinct large-object type - binary/text data is just String -
  // and this driver deliberately doesn't implement io.r2dbc.spi.Blob/Clob binding or extraction.
  // -----------------------------------------------------------------------------------------

  @Disabled("ClickHouse has no BLOB type; this driver does not implement io.r2dbc.spi.Blob binding")
  @Override
  public void blobInsert() {}

  @Disabled(
      "ClickHouse has no BLOB type; this driver does not implement io.r2dbc.spi.Blob extraction")
  @Override
  public void blobSelect() {}

  @Disabled("ClickHouse has no CLOB type; this driver does not implement io.r2dbc.spi.Clob binding")
  @Override
  public void clobInsert() {}

  @Disabled(
      "ClickHouse has no CLOB type; this driver does not implement io.r2dbc.spi.Clob extraction")
  @Override
  public void clobSelect() {}

  // -----------------------------------------------------------------------------------------
  // Generated keys: ClickHouse has no autoincrement/RETURNING-style mechanism to implement
  // Statement.returnGeneratedValues() against, so it inherits the R2DBC SPI's own default (throws
  // UnsupportedOperationException) - itself the honest answer here, not something to work around.
  // -----------------------------------------------------------------------------------------

  @Disabled(
      "ClickHouse has no generated-key mechanism; returnGeneratedValues() throws UnsupportedOperationException (the R2DBC SPI's own unoverridden default)")
  @Override
  public void returnGeneratedValues() {}

  @Disabled(
      "Same root cause as returnGeneratedValues(): the SPI default throws UnsupportedOperationException, not the IllegalArgumentException this TCK test expects for a null argument")
  @Override
  public void returnGeneratedValuesFails() {}

  // -----------------------------------------------------------------------------------------
  // Misc SPI edges this driver deliberately doesn't match today.
  // -----------------------------------------------------------------------------------------

  @Disabled(
      "This driver defers all bind-value handling to query encoding at execute() time (see ClickHouseQuery#withParameters) rather than validating a value's type eagerly inside bind() - bind(identifier, Class.class) does not synchronously throw IllegalArgumentException the way this TCK test expects")
  @Override
  public void bindFails() {}

  @Disabled(
      "ClickHouse's HTTP INSERT response carries no body/segments for Statement.execute() - writtenRows is only ever available via Result#getRowsUpdated(); this driver never emits a Result.UpdateCount segment (see ClickHouseResult's Javadoc)")
  @Override
  public void segmentInsertEmitsUpdateCount() {}

  @Disabled(
      "Not verified against this driver: ClickHouse's HTTP interface executes one statement per request and is not exercised here as returning multiple result sets for one semicolon-separated multi-statement query")
  @Override
  public void compoundStatement() {}
}
